create database bicycle_retail;
select * from bicycle_retail.orders;

-- task 3 Join orders, order_items, and products to display detailed line items-
use bicycle_retail;

select od.Customer_ID,op.quantity,op.Discount,op.List_Price,pd.Product_Name,pd.Product_ID,pd.Category_ID 
from bicycle_retail.order_items as op
inner join bicycle_retail.orders as od
on od.Order_ID = op.Order_ID
inner join bicycle_retail.product as pd
on pd.Product_ID = op.Product_ID;



-- task 4  Write a query to group sales (total_price) by each store_id
select o.store_ID ,sum(op.total_price) from bicycle_retail.order_items as op
left join orders as o
on o.order_ID=op.Order_ID
group by o.store_ID
order by sum(total_price) desc;

-- Task 5 Use ORDER BY and LIMIT to get the top 5 most sold products by quantity.--
 
select op.Product_ID,p.product_name,sum(op.quantity)*op.list_price  as top_sold_product
from bicycle_retail.product as p
right join bicycle_retail.order_items as op
on op.Product_ID =p.product_id 
group by op.product_ID,p.Product_Name,op.list_price
order by top_sold_product desc limit 5;

-- 
set sql_safe_updates=0;
alter table  bicycle_retail.customers add column full_name varchar(100);
update bicycle_retail.customers set full_name
=concat(First_Name,'',Last_Name);

--  task 6 For each customer, return total orders placed, total items purchased, and total revenue.
select c.full_name,c.customer_ID,count(distinct o.Order_ID) as total_sales ,sum(op.quantity) as total_purchase,sum(op.total_price)
from bicycle_retail.orders as o
right join bicycle_retail.customers as c
on o.Customer_ID=c.Customer_ID
right join bicycle_retail.order_items as op
on op.Order_ID=o.Order_ID
group by c.Customer_ID,c.full_name
order by total_sales desc;


-- task 7 Write a query to classify customers into spending brackets (e.g., low, medium, high).
select c.full_name,o.order_ID,sum(total_price) as spending_brackets ,
case when sum(total_price)  > 2000 then 'High'
when  sum(total_price) >=1200 then 'Medium' else 'Low'
end as customer_spending from bicycle_retail.order_items as od
inner join bicycle_retail.orders as o
on o.Order_ID=od.Order_ID
inner join bicycle_retail.customers as c
on c.Customer_ID=o.Customer_ID
group by c.full_name,o.Order_ID
order by spending_brackets ;

-- task 8 Analyze total revenue generated by each staff member based on their handled orders.
select s.staff_id ,sum(od.total_price) as staff_sale
from bicycle_retail.orders as o
inner join bicycle_retail.order_items as od
on od.Order_ID=o.Order_ID
inner join bicycle_retail.staffs as s
on o.Staff_ID=s.Staff_ID
group by s.staff_id ;


-- task 9 Write a query to list products where stock quantity < 10 in any store.
select s.store_id,s.product_id,p.product_name,s.quantity 
from bicycle_retail.stocks as s
right join bicycle_retail.product as p
on s.Product_ID=p.Product_ID
where s.Quantity<10;


select * from bicycle_retail.customer_segments;







